# Módulo 1: Análisis de datos en el ecosistema Python

### Sesión (3)

**18/09/2023**

# `Alejandro Sánchez Monzón`

---

In [1]:
import numpy as np

### **`Ejercicio 3.1`**

**`3.1.1`** Crea un array de tamaño (6x6) con elementos aleatorios entre 0 y 10 inclusive.  
**`3.1.2`** Calcula el total de bytes que ocupa la matriz.  
**`3.1.3`** Calcula la media y la desviación estándar de los valores presentes en la matriz.  
**`3.1.4`** Crea un nuevo vector, convirtiendo todos los valores del array creado en el primer paso en números decimales.

In [2]:
## Solución
# Ejercicio 3.1.1
x = np.random.randint(0, 11, (6,6))

print(x)

[[ 2  1  8  7  4  0]
 [10  8  3  9  2  3]
 [ 4  3  3  5  3  7]
 [ 0  6  1  7  2  0]
 [ 1  0  7  8 10 10]
 [ 1  0  7  2  4  5]]


In [3]:
## Solución
# Ejercicio 3.1.2
print("bytes que ocupa:", x.nbytes)

bytes que ocupa: 144


In [4]:
## Solución
# Ejercicio 3.1.3
print("media:", x.mean())
print("desviación:", x.std())

media: 4.25
desviación: 3.191786333700926


In [5]:
## Solución
# Ejercicio 3.1.4
y = np.array(x, dtype="float")

print(y)

[[ 2.  1.  8.  7.  4.  0.]
 [10.  8.  3.  9.  2.  3.]
 [ 4.  3.  3.  5.  3.  7.]
 [ 0.  6.  1.  7.  2.  0.]
 [ 1.  0.  7.  8. 10. 10.]
 [ 1.  0.  7.  2.  4.  5.]]


---

### **`Ejercicio 3.2`**

**`3.2.1`** Crea un array de tamaño (5x5) con todos los elementos iguales a 11, salvo el primero y el último que deben de ser iguales a 88.  
**`3.2.2`** Crea un array seleccionando todos los elementos excepto los de la primera fila y los de la primera columna.   
**`3.2.3`** Crea un nuevo array redimensionando y reordenando los elementos del array obtenido en el paso anterior para que el nuevo sea de tamaño (2x8).  
**`3.2.4`** Crea otro nuevo array con 8 elementos equidistantes entre 0 y 10.  
**`3.2.5`** Concatena el nuevo array creado en el paso enterior con el array redimensionado de tamaño (2x8) y convierte posteriormente los valores del nuevo vector concatenado en números enteros.  
**`3.2.6`** Separa el vector resultante en dos partes iguales. 

In [6]:
## Solución
# Ejercicio 3.2.1
x = np.full((5, 5), 11)

x[0, 0] = 88
x[-1, -1] = 88

print(x)

[[88 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 88]]


In [7]:
## Solución
# Ejercicio 3.2.2
y = x[1:, 1:]

print(y)

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]
 [11 11 11 88]]


In [8]:
## Solución
# Ejercicio 3.2.3
z = y.reshape(2, 8)

print(z)

[[11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 88]]


In [9]:
## Solución
# Ejercicio 3.2.4
e = np.linspace(0,10,8)

print(e)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [10]:
## Solución
# Ejercicio 3.2.5

# No sabía si usar 'int32' o 'int64', así que dejo solo 'int'.
res = np.vstack((z, e.astype("int")), dtype="int")

print(res)

[[11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 88]
 [ 0  1  2  4  5  7  8 10]]


In [11]:
## Solución
# Ejercicio 3.2.6
np.hsplit(res, 2)

[array([[11, 11, 11, 11],
        [11, 11, 11, 11],
        [ 0,  1,  2,  4]]),
 array([[11, 11, 11, 11],
        [11, 11, 11, 88],
        [ 5,  7,  8, 10]])]

---

### **`Ejercicio 3.3`**

**`3.3.1`** Crea un array de tamaño (3x4) de todos los números enteros entre 0 y 100 que sean múltiplos de 9.  
**`3.3.2`** Filtra todos los valores del vector creado en el paso anterior de la siguiente manera:  
- Si son valores mayores que cero y múltiplos de 5 se conservan sin cambios  
- En el caso contratio se sustituyen con el valor -1  

In [12]:
## Solución
# Ejercicio 3.3.1
array = np.arange(0, 100)
arr_multiplos = array[array % 9 == 0]

arr_redimensionado = arr_multiplos.reshape(3, 4)

print(arr_redimensionado)

# Solución alternativa (y en una línea):
# np.arange(0, 100, 9).reshape(3, 4)

[[ 0  9 18 27]
 [36 45 54 63]
 [72 81 90 99]]


In [13]:
## Solución
# Ejercicio 3.3.2
np.where((arr_redimensionado % 5 == 0) & (arr_redimensionado > 0), arr_redimensionado, -1)

array([[-1, -1, -1, -1],
       [-1, 45, -1, -1],
       [-1, -1, 90, -1]])